### ISSUE TITLE
Test Beta Release

### ISSUE THREAD

**Issue by danhamill** [HydrologicEngineeringCenter/DssToolkit#17]
I am interested in testing the beta release, but not sure how to launch the plugin.  I extracted the release zip folder into my dssvue directory:

![image](https://user-images.githubusercontent.com/11522898/130296825-d93f8e9a-5116-4946-97b8-1e75336bdaae.png)
 
In dssvue. I do not notice anything about the new plugin.

**Comment by ktarbet** [comment]
Here is a beta DSSvue with DSSExcel for testing/feedback

https://github.com/HydrologicEngineeringCenter/DSSExcelPlugin/releases/tag/v1.0.1-beta

docs: https://www.hec.usace.army.mil/confluence/dssvuedocs/latest/data-entry-import-and-export/dssexcel-beta/importing-dss-data

**Comment by danhamill** [comment]
Hey Guys I finally got around to do some testing with the DSSvue version 3.3.11 

Today I had DSSvue open with multiple DSS files.  When I launched the dssvue excel import, all of the other dss files I was not importing to were closed without warning.

**Comment by ktarbet** [comment]
@danhamill 

Thanks for your bug report.  We have a fix for this issue in the latest Beta version:

https://www.hec.usace.army.mil/software/hec-dssvue/downloads.aspx
